<?php

namespace Database\Seeders;

use App\Models\HR\Employee;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            // Store Admin (SADM)
            [
                'user_id' => 2,
                'store_id' => 1,
                'branch_id' => 1,
                'employee_number' => 'SADM-2026-00001',
                'fname' => 'Ahbram',
                'lname' => 'Carra',
                'phone' => '09172345678',
                'city' => 'Silang',
                'address' => '456 Admin Ave, Brgy. Project 4',
                'date_of_birth' => '1992-03-20',
                'gender' => 'male',
                'hire_date' => '2021-03-01',
                'role_id' => 2,
                'department' => 'Store Management',
                'employment_type' => 'full_time',
                'salary' => 55000.00,
                'bank_account' => '1234567891',
                'tax_id' => 'TAX-123-456-790',
                'emergency_contact_name' => 'Maria Carra',
                'emergency_contact_phone' => '09177543211',
                'emergency_contact_relationship' => 'Mother',
                'id_document_path' => '/uploads/ids/2_id.jpg',
                'contract_path' => '/uploads/contracts/2_contract.pdf',
                'status' => 'active',
                'termination_date' => null,
                'termination_reason' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                'deleted_by' => null,
            ],

            // Store Manager (SM)
            [
                'user_id' => 3,
                'store_id' => 1,
                'branch_id' => 1,
                'employee_number' => 'SM-2026-00001',
                'fname' => 'Adrian',
                'lname' => 'Lacea',
                'phone' => '09173456789',
                'city' => 'Imus',
                'address' => '789 Manager Rd, Brgy. Poblacion',
                'date_of_birth' => '1988-07-12',
                'gender' => 'male',
                'hire_date' => '2021-06-15',
                'role_id' => 3,
                'department' => 'Store Operations',
                'employment_type' => 'full_time',
                'salary' => 48000.00,
                'bank_account' => '1234567892',
                'tax_id' => 'TAX-123-456-791',
                'emergency_contact_name' => 'Elena Lacea',
                'emergency_contact_phone' => '09178543212',
                'emergency_contact_relationship' => 'Spouse',
                'id_document_path' => '/uploads/ids/3_id.jpg',
                'contract_path' => '/uploads/contracts/3_contract.pdf',
                'status' => 'active',
                'termination_date' => null,
                'termination_reason' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                'deleted_by' => null,
            ],

            // HR Manager (HR)
            [
                'user_id' => 4,
                'store_id' => 1,
                'branch_id' => 1,
                'employee_number' => 'HR-2026-00001',
                'fname' => 'Edwin',
                'lname' => 'Vasquez',
                'phone' => '09174567890',
                'city' => 'Silang',
                'address' => '321 HR St, Brgy. Plainview',
                'date_of_birth' => '1985-11-08',
                'gender' => 'male',
                'hire_date' => '2020-08-10',
                'role_id' => 4,
                'department' => 'Human Resources',
                'employment_type' => 'full_time',
                'salary' => 52000.00,
                'bank_account' => '1234567893',
                'tax_id' => 'TAX-123-456-792',
                'emergency_contact_name' => 'Luzviminda Vasquez',
                'emergency_contact_phone' => '09179543213',
                'emergency_contact_relationship' => 'Spouse',
                'id_document_path' => '/uploads/ids/4_id.jpg',
                'contract_path' => '/uploads/contracts/4_contract.pdf',
                'status' => 'active',
                'termination_date' => null,
                'termination_reason' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                'deleted_by' => null,
            ],

            // Accountant (ACT)
            [
                'user_id' => 5,
                'store_id' => 1,
                'branch_id' => 1,
                'employee_number' => 'ACT-2026-00001',
                'fname' => 'MC',
                'lname' => 'Mendoza',
                'phone' => '09175678901',
                'city' => 'Imus',
                'address' => '654 Finance Ave, Brgy. Kapitolyo',
                'date_of_birth' => '1991-09-25',
                'gender' => 'female',
                'hire_date' => '2022-01-20',
                'role_id' => 5,
                'department' => 'Finance',
                'employment_type' => 'full_time',
                'salary' => 45000.00,
                'bank_account' => '1234567894',
                'tax_id' => 'TAX-123-456-793',
                'emergency_contact_name' => 'Carlos Mendoza',
                'emergency_contact_phone' => '09170543214',
                'emergency_contact_relationship' => 'Father',
                'id_document_path' => '/uploads/ids/5_id.jpg',
                'contract_path' => '/uploads/contracts/5_contract.pdf',
                'status' => 'active',
                'termination_date' => null,
                'termination_reason' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                'deleted_by' => null,
            ],

            // Cashier (CSH)
            [
                'user_id' => 6,
                'store_id' => 1,
                'branch_id' => 1,
                'employee_number' => 'CSH-2026-00001',
                'fname' => 'Cash',
                'lname' => 'Gshock',
                'phone' => '09176789012',
                'city' => 'Naic',
                'address' => '987 Cashier Lane, Brgy. BGC',
                'date_of_birth' => '1995-02-18',
                'gender' => 'male',
                'hire_date' => '2022-03-25',
                'role_id' => 6,
                'department' => 'Sales',
                'employment_type' => 'full_time',
                'salary' => 25000.00,
                'bank_account' => '1234567895',
                'tax_id' => 'TAX-123-456-794',
                'emergency_contact_name' => 'Rosa Gshock',
                'emergency_contact_phone' => '09171543215',
                'emergency_contact_relationship' => 'Mother',
                'id_document_path' => '/uploads/ids/6_id.jpg',
                'contract_path' => '/uploads/contracts/6_contract.pdf',
                'status' => 'active',
                'termination_date' => null,
                'termination_reason' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                'deleted_by' => null,
            ],

            // Warehouse Manager (WHM)
            [
                'user_id' => 7,
                'store_id' => 1,
                'branch_id' => 1,
                'employee_number' => 'WHM-2026-00001',
                'fname' => 'Ware',
                'lname' => 'House',
                'phone' => '09177890123',
                'city' => 'Tagaytay',
                'address' => '147 Warehouse Dr, Brgy. Karuhatan',
                'date_of_birth' => '1993-12-03',
                'gender' => 'male',
                'hire_date' => '2022-06-10',
                'role_id' => 7,
                'department' => 'Logistics',
                'employment_type' => 'full_time',
                'salary' => 28000.00,
                'bank_account' => '1234567896',
                'tax_id' => 'TAX-123-456-795',
                'emergency_contact_name' => 'Jose House',
                'emergency_contact_phone' => '09172543216',
                'emergency_contact_relationship' => 'Father',
                'id_document_path' => '/uploads/ids/7_id.jpg',
                'contract_path' => '/uploads/contracts/7_contract.pdf',
                'status' => 'active',
                'termination_date' => null,
                'termination_reason' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                'deleted_by' => null,
            ],

            // Inventory Staff (INV)
            [
                'user_id' => 8,
                'store_id' => 1,
                'branch_id' => 1,
                'employee_number' => 'INV-2026-00001',
                'fname' => 'Invent',
                'lname' => 'Ory',
                'phone' => '09178901234',
                'city' => 'Dasmarinas',
                'address' => '258 Inventory St, Brgy. 176',
                'date_of_birth' => '1994-04-22',
                'gender' => 'male',
                'hire_date' => '2022-08-15',
                'role_id' => 8,
                'department' => 'Inventory',
                'employment_type' => 'full_time',
                'salary' => 28000.00,
                'bank_account' => '1234567897',
                'tax_id' => 'TAX-123-456-796',
                'emergency_contact_name' => 'Elena Ory',
                'emergency_contact_phone' => '09173543217',
                'emergency_contact_relationship' => 'Mother',
                'id_document_path' => '/uploads/ids/8_id.jpg',
                'contract_path' => '/uploads/contracts/8_contract.pdf',
                'status' => 'active',
                'termination_date' => null,
                'termination_reason' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                'deleted_by' => null,
            ],

            // Supplier Coordinator (SUP)
            [
                'user_id' => 9,
                'store_id' => 1,
                'branch_id' => 1,
                'employee_number' => 'SUP-2026-00001',
                'fname' => 'Supp',
                'lname' => 'Coor',
                'phone' => '09179012345',
                'city' => 'Silang',
                'address' => '369 Supply Blvd, Brgy. 101',
                'date_of_birth' => '1990-10-11',
                'gender' => 'male',
                'hire_date' => '2022-10-01',
                'role_id' => 9,
                'department' => 'Procurement',
                'employment_type' => 'full_time',
                'salary' => 32000.00,
                'bank_account' => '1234567898',
                'tax_id' => 'TAX-123-456-797',
                'emergency_contact_name' => 'Maria Coor',
                'emergency_contact_phone' => '09174543218',
                'emergency_contact_relationship' => 'Spouse',
                'id_document_path' => '/uploads/ids/9_id.jpg',
                'contract_path' => '/uploads/contracts/9_contract.pdf',
                'status' => 'active',
                'termination_date' => null,
                'termination_reason' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                'deleted_by' => null,
            ],

            // Sales Staff (SAL)
            [
                'user_id' => 10,
                'store_id' => 1,
                'branch_id' => 1,
                'employee_number' => 'SAL-2026-00001',
                'fname' => 'Sales',
                'lname' => 'Domingo',
                'phone' => '09170123456',
                'city' => 'Amadeo',
                'address' => '159 Sales St, Brgy. BF',
                'date_of_birth' => '1996-08-30',
                'gender' => 'male',
                'hire_date' => '2023-01-15',
                'role_id' => 10,
                'department' => 'Sales',
                'employment_type' => 'full_time',
                'salary' => 26000.00,
                'bank_account' => '1234567899',
                'tax_id' => 'TAX-123-456-798',
                'emergency_contact_name' => 'Teresa Domingo',
                'emergency_contact_phone' => '09175543219',
                'emergency_contact_relationship' => 'Mother',
                'id_document_path' => '/uploads/ids/10_id.jpg',
                'contract_path' => '/uploads/contracts/10_contract.pdf',
                'status' => 'active',
                'termination_date' => null,
                'termination_reason' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                'deleted_by' => null,
            ],

            // Delivery Staff (DLV)
            [
                'user_id' => 11,
                'store_id' => 1,
                'branch_id' => 1,
                'employee_number' => 'DLV-2026-00001',
                'fname' => 'Delivery',
                'lname' => 'Padala',
                'phone' => '09171234568',
                'city' => 'Bacoor',
                'address' => '753 Delivery Hub, Brgy. Almanza',
                'date_of_birth' => '1997-05-17',
                'gender' => 'male',
                'hire_date' => '2023-03-20',
                'role_id' => 11,
                'department' => 'Logistics',
                'employment_type' => 'full_time',
                'salary' => 24000.00,
                'bank_account' => '1234567900',
                'tax_id' => 'TAX-123-456-799',
                'emergency_contact_name' => 'Pedro Padala',
                'emergency_contact_phone' => '09176543220',
                'emergency_contact_relationship' => 'Father',
                'id_document_path' => '/uploads/ids/11_id.jpg',
                'contract_path' => '/uploads/contracts/11_contract.pdf',
                'status' => 'active',
                'termination_date' => null,
                'termination_reason' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
                'deleted_by' => null,
            ],
        ];

        foreach ($employees as $employee) {
            Employee::create($employee);
        }
    }
}
